apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 3001
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nachofan/order:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/wemo-scooter-order?schema=public
            - name: RABBITMQ_URL
              value: amqp://admin:password@rabbitmq:5672
