apiVersion: v1
kind: Service
metadata:
  name: scooter-rent-service
spec:
  ports:
    - port: 3000
  selector:
    app: scooter-rent-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scooter-rent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scooter-rent-service
  template:
    metadata:
      labels:
        app: scooter-rent-service
    spec:
      containers:
        - name: scooter-rent-service
          image: nachofan/scooter-rent:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/wemo-scooter-rent?schema=public
            - name: RABBITMQ_URL
              value: amqp://admin:password@rabbitmq:5672
