apiVersion: apps/v1
kind: Deployment
metadata:
  name: scooter-rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scooter-rent
  template:
    metadata:
      labels:
        app: scooter-rent
    spec:
      containers:
        - name: scooter-rent
          image: nachofan/scooter-rent:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgres://wemo:wemo@postgres:5432/wemo-scooter-rent"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
          command:
            [ "sh", "-c", "npx prisma migrate dev && npx prisma db seed && npm run start" ]

---
apiVersion: v1
kind: Service
metadata:
  name: scooter-rent-service
spec:
  selector:
    app: scooter-rent
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
